---
- name: Simplified AWS VM Provisioning
  hosts: localhost
  gather_facts: true

  vars:
    vm_name: "{{ vm_name | default('test-vm') }}"
    vm_flavor_raw: "{{ flavor | default('small') }}"
    vm_os: "{{ os | default('ubuntu-22.04') }}"
    cloud_init_raw: "{{ cloud_init | default('#cloud-config\npackage_upgrade: true') }}"

    os_ami_map:
      ubuntu-22.04: "ami-0c7217cdde317cfec"
      redhat-9: "ami-0b0af3577fe5e3532"

    flavor_map:
      small: "t3.small"
      medium: "t3.medium"
      large: "t3.large"

  tasks:
    - name: Validate OS selection
      fail:
        msg: "Unsupported OS '{{ vm_os }}'. Valid options: {{ os_ami_map.keys() | list }}"
      when: vm_os not in os_ami_map

    - name: Prepare cloud-init
      set_fact:
        cloud_init: "{{ cloud_init_raw | b64encode }}"

    - name: Clone Terraform project
      ansible.builtin.git:
        repo: https://github.com/khalilMaat/cloud-vm-provision.git
        dest: /tmp/cloud-vm-provision
        force: yes

    # - name: Install Terraform
    #   ansible.builtin.shell: |
    #     curl -O https://releases.hashicorp.com/terraform/1.5.7/terraform_1.5.7_linux_amd64.zip
    #     unzip terraform_1.5.7_linux_amd64.zip -d /usr/local/bin
    #     rm terraform_1.5.7_linux_amd64.zip
    #     terraform version
    #   args:
    #     executable: /bin/bash

    - name: Initialize Terraform
      command: terraform init
      args:
        chdir: "/tmp/cloud-vm-provision/terraform"

    - name: Initialize and apply Terraform configuration
      community.general.terraform:
        project_path: /tmp/cloud-vm-provision/terraform
        state: present
        force_init: true
        variables:
          vm_name: "{{ vm_name }}"
          vm_flavor: "{{ flavor_map[vm_flavor_raw] | default('t3.micro') }}"
          cloud_init: "{{ cloud_init }}"
          ami_id: "{{ os_ami_map[vm_os] }}"

    # - name: Apply Terraform configuration
    #   command: |
    #     terraform apply -auto-approve \
    #     -var="vm_name={{ vm_name }}" \
    #     -var="vm_flavor={{ flavor_map[vm_flavor_raw] | default('t3.micro') }}" \
    #     -var="cloud_init={{ cloud_init }}" \
    #     -var="ami_id={{ os_ami_map[vm_os] }}"
    #   args:
    #     chdir: "/tmp/cloud-vm-provision/terraform"
