---
- name: Simplified AWS VM Provisioning
  hosts: ansible1
  gather_facts: false

  vars:
    vm_name: "{{ vm_name }}"
    vm_flavor_raw: "{{ vm_flavor }}"
    cloud_init_raw: "{{ cloud_init }}"

    # Direct AMI IDs for us-east-1 (update as needed)
    os_ami_map:
      ubuntu-22.04: "ami-0c7217cdde317cfec" # Ubuntu 22.04 LTS
      redhat-9: "ami-0b0af3577fe5e3532" # RHEL 9
      # Add more AMIs as needed

      # Instance type mapping
    flavor_map:
      small: "t3.small"
      medium: "t3.medium"
      large: "t3.large"

  tasks:
    - name: Validate OS selection
      fail:
        msg: "Unsupported OS '{{ vm_os }}'. Valid options: {{ os_ami_map.keys() | list }}"
      when: vm_os not in os_ami_map

    - name: Prepare cloud-init
      set_fact:
        cloud_init: "{{ cloud_init_raw | b64encode }}"

    - name: Clone Terraform project
      ansible.builtin.git:
        repo: https://github.com/khalilMaat/cloud-vm-provision.git
        dest: /tmp/cloud-vm-provision
        force: yes

    - name: Run Terraform
      community.general.terraform:
        project_path: "/tmp/cloud-vm-provision/terraform"
        force_init: true
        state: present
        variables:
          vm_name: "{{ vm_name }}"
          vm_flavor: "{{ flavor_map[vm_flavor] | default('t3.micro') }}"
          cloud_init: "{{ cloud_init | b64encode }}"
          ami_id: "{{ os_ami_map[vm_os] }}"
